<?php

namespace Pitech\Fedex\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusRepository extends EntityRepository
{
}
