pitech_fedex_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PitechFedexMainBundle:Default:index }

pitech_fedex_main_times:
    pattern:  /map/{name}
    defaults: { _controller: PitechFedexMainBundle:Map:getTimes }

pitech_fedex_main_map:
    pattern:  /map
    defaults: { _controller: PitechFedexMainBundle:Map:index }

pitech_get_kml:
    pattern:  /getKml
    defaults: { _controller: PitechFedexMainBundle:Map:getKMLfile }

pitech_get_kml:
    pattern:  /parse
    defaults: { _controller: PitechFedexMainBundle:Map:parseGPX }

pitech_get_route_coords:
    pattern:  /getRoutesCoords
    defaults: { _controller: PitechFedexMainBundle:Map:getRoutes }
