pitech_fedex_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PitechFedexMainBundle:Default:index }

pitech_fedex_main_map:
    pattern:  /map
    defaults: { _controller: PitechFedexMainBundle:Map:index }
